package com.medical.demo.model;

public class SysRolePermissionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.roleId
     *
     * @mbg.generated Tue Mar 03 16:33:35 CST 2020
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.permissionId
     *
     * @mbg.generated Tue Mar 03 16:33:35 CST 2020
     */
    private Integer permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.roleId
     *
     * @return the value of sys_role_permission.roleId
     *
     * @mbg.generated Tue Mar 03 16:33:35 CST 2020
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.roleId
     *
     * @param roleid the value for sys_role_permission.roleId
     *
     * @mbg.generated Tue Mar 03 16:33:35 CST 2020
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.permissionId
     *
     * @return the value of sys_role_permission.permissionId
     *
     * @mbg.generated Tue Mar 03 16:33:35 CST 2020
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.permissionId
     *
     * @param permissionid the value for sys_role_permission.permissionId
     *
     * @mbg.generated Tue Mar 03 16:33:35 CST 2020
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}